#!/bin/bash

# --- CONFIGURATION ---
# --- CONFIGURATION ---
# Read IPs from the file generated by Tofu
if [[ -f "ips.txt" ]]; then
    mapfile -t NODES < ips.txt
else
    echo "Error: ips.txt not found. Run tofu apply first."
    exit 1
fi


USER="ubuntu"
SSH_KEY="~/.ssh/id_rsa"
MASTER_IP=${NODES[0]}

TYPE=$1

if [[ -z "$TYPE" ]]; then
    echo "Usage: ./deploy.sh [k0s|k3s|rke2|cleanup]"
    exit 1
fi

# Helper to update the global kubeconfig
update_global_kubeconfig() {
    local SRC_CONFIG=$1
    mkdir -p ~/.kube
    cp "$SRC_CONFIG" ~/.kube/config
    rm -rf ~/.kube/cache  # Clear cache to prevent certificate errors
    echo "------------------------------------------------------------"
    echo "Global kubeconfig updated! You can now run: kubectl get nodes"
    echo "------------------------------------------------------------"
}

check_already_installed() {
    if ssh -o ConnectTimeout=5 $USER@$MASTER_IP "pgrep -f 'k3s|k0s|rke2'" > /dev/null 2>&1; then
        echo "ERROR: A cluster is already running. Run ./deploy.sh cleanup first."
        exit 1
    fi
}

# --- 1. K0S ---

install_k0s() {
    check_already_installed
    echo "Updating k0sctl.yaml for ${#NODES[@]} nodes..."

    for i in "${!NODES[@]}"; do
        IP="${NODES[$i]}"
        # The '/number' at the end of sed targets the N-th occurrence
        OCCURRENCE=$((i + 1))
        
        echo "Assigning Node $i ($IP) to k0sctl.yaml slot $OCCURRENCE..."
        sed -i "s/address: .*/address: $IP/$OCCURRENCE" k0sctl.yaml
    done

    k0sctl apply --config k0sctl.yaml
    k0sctl kubeconfig --config k0sctl.yaml > k0s.config
    update_global_kubeconfig "k0s.config"
}
# --- 2. K3S ---
# --- 2. K3S ---
install_k3s() {
    check_already_installed
    echo "Installing K3S Master..."
    ssh $USER@$MASTER_IP "curl -sfL https://get.k3s.io | sh -"
    
    TOKEN=$(ssh $USER@$MASTER_IP "sudo cat /var/lib/rancher/k3s/server/node-token")
    
    for IP in ${NODES[@]:1}; do
        echo "Joining worker $IP..."
        ssh $USER@$IP "curl -sfL https://get.k3s.io | K3S_URL=https://$MASTER_IP:6443 K3S_TOKEN=$TOKEN sh -"
    done

    echo "Fetching kubeconfig..."
    # STEP 1: Copy to a temp location and change ownership so we can download it
    ssh $USER@$MASTER_IP "sudo cp /etc/rancher/k3s/k3s.yaml /tmp/k3s.yaml && sudo chown $USER:$USER /tmp/k3s.yaml"
    
    # STEP 2: Download from the temp location
    scp $USER@$MASTER_IP:/tmp/k3s.yaml ./k3s.config
    
    # STEP 3: Clean up the temp file on the remote server
    ssh $USER@$MASTER_IP "rm /tmp/k3s.yaml"

    # STEP 4: Fix the IP and update local config
    sed -i "s/127.0.0.1/$MASTER_IP/g" ./k3s.config
    update_global_kubeconfig "k3s.config"
}
# --- 3. RKE2 ---
# --- 3. RKE2 ---
install_rke2() {
    check_already_installed
    echo "Installing RKE2 Master on $MASTER_IP..."
    # Added 'sudo' before 'sh -'
    ssh $USER@$MASTER_IP "curl -sfL https://get.rke2.io | sudo sh - && sudo systemctl enable rke2-server --now"
    
    echo "Waiting 20 seconds for RKE2 to initialize and generate token..."
    sleep 20
    
    TOKEN=$(ssh $USER@$MASTER_IP "sudo cat /var/lib/rancher/rke2/server/node-token")
    
    for IP in ${NODES[@]:1}; do
        echo "Configuring and joining worker $IP..."
        # Create config directory and write join config
        ssh $USER@$IP "sudo mkdir -p /etc/rancher/rke2/ && echo -e \"server: https://$MASTER_IP:9345\ntoken: $TOKEN\" | sudo tee /etc/rancher/rke2/config.yaml"
        
        # Install RKE2 Agent with sudo
        ssh $USER@$IP "curl -sfL https://get.rke2.io | sudo INSTALL_RKE2_TYPE='agent' sh - && sudo systemctl enable rke2-agent --now"
    done

    echo "Fetching RKE2 kubeconfig..."
    # STEP 1: Copy to temp and change ownership
    ssh $USER@$MASTER_IP "sudo cp /etc/rancher/rke2/rke2.yaml /tmp/rke2.yaml && sudo chown $USER:$USER /tmp/rke2.yaml"
    
    # STEP 2: Download
    scp $USER@$MASTER_IP:/tmp/rke2.yaml ./rke2.config
    
    # STEP 3: Remote Cleanup
    ssh $USER@$MASTER_IP "rm /tmp/rke2.yaml"

    # STEP 4: Fix IP and update local ~/.kube/config
    sed -i "s/127.0.0.1/$MASTER_IP/g" ./rke2.config
    update_global_kubeconfig "rke2.config"
}
# --- 4. CLEANUP ---
cleanup() {
    for IP in "${NODES[@]}"; do
        echo "Cleaning up node: $IP"
        ssh -t $USER@$IP "
            # 1. Stop all possible services
            sudo systemctl stop k3s k3s-agent rke2-server rke2-agent k0scontroller k0sworker 2>/dev/null
            sudo k0s stop 2>/dev/null
            
            # 2. Dynamic Unmount - This targets k3s, k0s, and RKE2 (rancher)
            for mount in \$(mount | grep -E 'k0s|containerd|kubelet|rancher|rke2' | awk '{print \$3}'); do
                sudo umount -l \$mount 2>/dev/null
            done

            # 3. Run RKE2/K3S specific uninstallers if they exist
            [ -f /usr/local/bin/k3s-uninstall.sh ] && sudo /usr/local/bin/k3s-uninstall.sh
            [ -f /usr/local/bin/rke2-uninstall.sh ] && sudo /usr/local/bin/rke2-uninstall.sh
            sudo k0s reset 2>/dev/null
            
            # 4. Final Nuclear Wipe (Added /run/rke2)
            sudo rm -rf /var/lib/rancher /var/lib/k0s /etc/rancher /etc/k0s /run/k0s /run/k3s /run/rke2 /var/lib/kubelet 2>/dev/null
            
            sudo systemctl daemon-reload
        "
    done
    rm -f *.config ~/.kube/config
    echo "Cleanup complete. Environment is fresh."
}
case $TYPE in
    k0s) install_k0s ;;
    k3s) install_k3s ;;
    rke2) install_rke2 ;;
    cleanup) cleanup ;;
esac
