apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: proxmox-k8s-cluster
spec:
  hosts:
  - role: controller
    ssh:
      address: 192.168.80.20
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
  - role: worker
    ssh:
      address: 192.168.80.21
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
  - role: worker
    ssh:
      address: 192.168.80.22
      user: ubuntu
      keyPath: ~/.ssh/id_rsa
  k0s:
    config:
      spec:
        telemetry:
          enabled: false # Optional: disable tracking
